name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.0.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - numpy=1.24.2
  - pip=20.3.3
  - jupyterlab=3.0.10
  - pip:
      - wandb==0.13.10
